---
substitutions:
  description: TBD
  device: TBD
  location: TBD
  name: TBD
  reboot_timeout: 1h
  update_interval: 10min

esphome:
  comment: ${description}
  name: ${device}
  name_add_mac_suffix: false
  platform: ESP8266
  project:
    name: TBD
    version: 0.0

esp8266:
  board: esp01_1m
  restore_from_flash: true

<<: !include common/common.yaml